image: golang:1.8

variables:
  REPO_NAME: github.com/uninett/goidc-proxy

before_script:
  - go version
  - echo $CI_PROJECT_DIR
  - curl https://glide.sh/get | sh
  - mkdir -p $GOPATH/src/$REPO_NAME
  - mv $CI_PROJECT_DIR/* $GOPATH/src/$REPO_NAME
  - cd $GOPATH/src/$REPO_NAME
  - export OUR_VERSION=${CI_BUILD_TAG:-$CI_BUILD_REF}
  - echo "Setting version to $OUR_VERSION"

stages:
  - test
  - build
  - deploy

test-project:
  stage: test
  script:
    - cp goidc.json.example goidc.json
    - glide install
    - go get -v github.com/go-playground/overalls
    - overalls -project=$REPO_NAME -ignore=.git,.glide,vendor -debug -- -race -v
    - go tool cover -func=overalls.coverprofile

build-project:
  stage: build
  script:
    - glide install
    - go build -o $CI_PROJECT_DIR/goidc-proxy
  artifacts:
    paths:
      - goidc-proxy

deploy-testing:
  stage: deploy
  script:
    - echo "$DEPLOY_KEY" > ssh-private-key
    - chmod 0600 ssh-private-key
    - echo "$TESTING_HOSTKEY" > ssh-known-hosts
    - ssh -o GlobalKnownHostsFile=ssh-known-hosts -i ssh-private-key goidc-deploy@$TESTING_HOST /bin/mkdir -p /opt/goidc-proxy-deploys/$OUR_VERSION
    - scp -o GlobalKnownHostsFile=ssh-known-hosts -i ssh-private-key goidc-proxy goidc-deploy@$TESTING_HOST:/opt/goidc-proxy-deploys/$OUR_VERSION/
    - rm ssh-private-key ssh-known-hosts
  environment:
    name: testing
  only:
    - master
